import 'package:flutter/material.dart';
import '../../../../core/theme/neumorphic_theme.dart';

class TermsOfServicePage extends StatelessWidget {
  const TermsOfServicePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            NeumorphicTheme.backgroundColor,
            NeumorphicTheme.surfaceColor,
            NeumorphicTheme.backgroundColor,
          ],
        ),
      ),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          elevation: 0,
          title: const Text('Terms of Service', 
            style: TextStyle(color: NeumorphicTheme.textPrimary, fontWeight: FontWeight.bold)),
          leading: IconButton(
            icon: const Icon(Icons.arrow_back_ios, color: NeumorphicTheme.textPrimary),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        body: SingleChildScrollView(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildSectionTitle('Last Updated: April 2026'),
              const SizedBox(height: 24),
              _buildContentText(
                'By using the Lugmatic mobile application and its associated services, you agree to be bound by these Terms of Service. Please read them carefully.',
              ),
              const SizedBox(height: 32),
              _buildSectionTitle('1. User Conduct'),
              _buildContentText(
                '• You are responsible for maintaining the confidentiality of your account.\n'
                '• You must not upload or broadcast content that violates copyrights, is defamatory, or promotes hate speech.\n'
                '• Lugmatic reserves the right to suspend accounts that violate these guidelines.',
              ),
              const SizedBox(height: 32),
              _buildSectionTitle('2. Content Ownership'),
              _buildContentText(
                '• Artists retain ownership of their original music and live performances.\n'
                '• By uploading content to Lugmatic, you grant us a non-exclusive, worldwide license to stream and distribute your content to our users.',
              ),
              const SizedBox(height: 32),
              _buildSectionTitle('3. Virtual Coins & Gifting'),
              _buildContentText(
                '• Virtual coins purchased on the platform have no real-world monetary value outside the Lugmatic ecosystem.\n'
                '• Coin purchases are final and non-refundable, except where required by law.',
              ),
              const SizedBox(height: 32),
              _buildSectionTitle('4. Disclaimers'),
              _buildContentText(
                'Lugmatic is provided "as is" without warranties of any kind. We do not guarantee uninterrupted service and are not liable for any content generated by users or artists.',
              ),
              const SizedBox(height: 32),
              _buildSectionTitle('5. Changes to Terms'),
              _buildContentText(
                'We may update these terms from time to time. Your continued use of the app following any changes constitutes acceptance of the new terms.',
              ),
              const SizedBox(height: 48),
              _buildContentText(
                'If you have any questions regarding these terms, please contact us at legal@lugmaticmusic.com.',
              ),
              const SizedBox(height: 48),
              Center(
                child: Text(
                  '© 2026 Lugmatic Music. All rights reserved.',
                  style: TextStyle(color: NeumorphicTheme.textTertiary, fontSize: 12),
                ),
              ),
              const SizedBox(height: 24),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Text(
      title,
      style: const TextStyle(
        color: NeumorphicTheme.primaryAccent,
        fontSize: 18,
        fontWeight: FontWeight.bold,
      ),
    );
  }

  Widget _buildContentText(String text) {
    return Text(
      text,
      style: const TextStyle(
        color: NeumorphicTheme.textSecondary,
        fontSize: 15,
        height: 1.6,
      ),
    );
  }
}
